### ISSUE TITLE
Integrity doesn't work when you use it wrong

### ISSUE THREAD

**Issue by MarkBaggett** [sans-sroc/integrity#12]
(sarcasm intended in issue title)

But seriously, I suspect authors will try things like passing the path they want you to verify as the option.  It would be nice if it just printed the help if they do something like this...

```
(media_processor) C:\Users\User\Desktop>integrity.exe .\SEC511.21.1
Enter a Courseware Version Identifier (e.g., 'SEC123-21-01'): SEC511.21.1
[+] Working directory: .
Cannot open file
.txt: The filename, directory name, or volume label syntax is incorrect.

goroutine 1 [running]:
main.check(0xf0e7c0, 0xc0000aa000, 0xee8114, 0x10)
        /home/runner/work/integrity/integrity/integrity.go:25 +0xcb
main.createVerFile(0xc00000c440, 0x1a)
        /home/runner/work/integrity/integrity/integrity.go:51 +0x12b
main.main()
        /home/runner/work/integrity/integrity/integrity.go:255 +0x9d3

**Comment by ekristen** [comment]
This could be handled by moving to urfave/cli/v2 or spf13/cobra, it's designed to handle these edge cases when the appropriate information hasn't been provided and drop usage. 

cobra is more intuitive and simple to get started, urfave is a bit less but more powerful in many different ways.
