### ISSUE TITLE
Mac v1.0.6 seems to have an issue

### ISSUE THREAD

**Issue by mark-hallman** [sans-sroc/integrity#17]
Guys,

I was looking at the changes in the cli syntax for the new version of integrity to determine what change the author's user manual needs. The updates to the manual are mostly done, I just need a few screenshots.  I downloaded the 1.0.6 macOS version and tried to use it.  Not working for me.  It might be a user error but I can't see any errors in my command line.

Issue:  After entering the command line and pressing enter I get the "Enter a courseware ID..." message.  This occurs not just for entering a `create` or `version` command but for commands like `help` and `version` too.  See screenshot.

<img width="826" alt="image" src="https://user-images.githubusercontent.com/16808320/116781965-f71bde80-aa4b-11eb-8ed1-cd1d2b21c15a.png">

Also,  if it is OK with you,  I'm going to modify the examples section of the Readme.md and submit it as a pull request.  I would prefer to have course numbers or a pattern for the required course number structure in the examples. The "TEST" is not working for me.  That may not have been intended to be final but rather an example for us. 

One more thing... can we drop the `-v` option for version?  We have the `version` command and the `--version` switch.  The `-v` might be mistaken for `verify` by those who have used bitfit for years.

-Mark

**Comment by ekristen** [comment]
I’m a bit confused by your messaging, I’ll try and sort it out.

Do you have a compiled version of 2.0.0 you are using? Based on your screenshot it appears you are using 1.0.6 as it is 2.0.0.

The prompt for courseware version is gone in 2.0.0 it’s handled by -c and can be anything. A PR to update the instructions is fine by me? 

I’m not sure if we can drop the -v but I’ll look, it’s built into the CLI framework.

**Comment by mark-hallman** [comment]
Yes,  I can see the confusion.  When I went to get the latest version at 6 this morning, V2 was not there.  Maybe browser cache was still showing me the 1.0.6 since I looked at the readme last night.  \_(ツ)_/¯

I'll grab v2 now.  Thanks for the response.

**Comment by ekristen** [comment]
@mark-hallman think we are good now yes?

**Comment by mark-hallman** [comment]
Yes,  we are good.  Closing this.
