### ISSUE TITLE
help consistency

### ISSUE THREAD

**Issue by philhagen** [sans-sroc/integrity#20]
why are there --help and 'integrity help'?  what is the difference?

**Comment by ekristen** [comment]
They are basically just aliases of each other `integrity help`, `integrity h` and `integrity -h` (this last one is pretty standard). They happen to be the default built in help behavior of the CLI tool for the most command help access methods.

The first two `integrity help` and `integrity h` are aliases and are a command of their own that accepts an optional argument of a subcommand to get it's help text, like `integrity help create`.

The third one is just your typical -h switch on the actual command itself, ie `integrity validate -h`

**Comment by mark-hallman** [comment]
I would suggest that we pick one method and go with that.  The aliases are not needed.  I looked  forensic cli tools like Zimmerman, Volitality, and even Docker cli and I can't find examples of this kind of duplication.  I'm not saying it's wrong,  just unnecessary.  If one was general help and the other was command specific help, it would make sense to me.

**Comment by ekristen** [comment]
I can look if one or the other can be disabled. It’s built in.

For my own educational and understanding. What’s the concern about the help being accessible in different ways?

**Comment by philhagen** [comment]
honestly, it's just confusing...  the long/short options like `-h` and `--help` are pretty well established but we need the docs to reflect just one method.  if all of our docs refer to `integrity help` and we just don't show the other options, that's ok.  but having multiples shown in the output and documentation is confusing.
