### ISSUE TITLE
empty "get_first" is unpredictable? why?

### ISSUE THREAD

**Issue by philhagen** [sans-sroc/integrity#21]
docs state that an empty "get_first" directory is unpredictable.  make it predictable - quit if it's empty maybe?

**Comment by mark-hallman** [comment]
I have removed the sentence from the user document about an empty get_first folder.  We were relying on the user to not create a get_first folder and leave it empty.  Integrity needs to perform this empty get_first folder verification and process accordingly.

Currently, integrity will create three verification files, including VERSION-XXX.Y.Z-first.txt, even if the get_first folder is empty.  What we need is for integrity to determine if there are files in the get_first folder.  If there are no files in the folder,  then continue with single ISO processing resulting in a single verification file.
