### ISSUE TITLE
cross-platform validation still causes failure

### ISSUE THREAD

**Issue by philhagen** [sans-sroc/integrity#28]
in v2.1.1, a checksum file created on macOS will fail validation run on Windows.

**Comment by philhagen** [comment]
every entry in the checksum file is reported as "missing" with the forward slash and "added" wit the backslash

**Comment by ekristen** [comment]
The master branch had a universal fix for this.

Can you test that code?

**Comment by ekristen** [comment]
This is fixed in `main`, validated with @philhagen via slack, closing out.
