### ISSUE TITLE
Suggestion: Ditch courseware version in the tool

### ISSUE THREAD

**Issue by ekristen** [sans-sroc/integrity#36]
I don't think it makes sense to use the courseware version in the tool. It actually has a couple negative impacts. 

First the tool generates the versioning files in the directory specified by the tool, while you can change the courseware version and end up with multiple version files, they files are only valid for the directory for which they are in anyways.

Second it makes predictability for the tool impossible, you have to know the courseware version to be able to run a validation.

**I suggest we move to a standard format like `integrity.txt` `integrity-part.txt` and `integrity-first.txt`.**

This has a couple benefits.

1. The commands to create/validate are easier, `-c` is no longer needed.
2. @MarkBaggett from a programmatic standpoint can simply look for those file names instead of having to know courseware identifiers. 

Ultimately we store content by version anyways, so if we are syncing down a folder TEST101.1.1 we have the courseware identifier right there, furthermore, if we do not want to rely on folder names I would suggest something like `.courseware-version` file in the directory or something, again this makes it a predictable path from a programmatic standpoint to know where to glean the version information from.

/cc @philhagen @mark-hallman @MarkBaggett

**Comment by philhagen** [comment]
that's going to require a ton of outside coordination and makes an assumption that directory names are correct.  we can approach this as an idea/suggestion, but it's not our call to make.

**Comment by philhagen** [comment]
I think that if we can introduce the content of the `-d` flag, expanded to absolute path, this may be feasbile.  something like a comment line.
