### ISSUE TITLE
required format not displayed

### ISSUE THREAD

**Issue by philhagen** [sans-sroc/integrity#39]
```
./integrity create -n test
FATA[0000] test does not match the required format
```

should show example of required format.  like should be in the `--help` output on the `--name`/`-n` flag as well

**Comment by ekristen** [comment]
Added to the v3 branch, latest binaries can be retrieved from the GitHub Actions after the actions are complete. https://github.com/sans-sroc/integrity/actions/runs/850257437

**Comment by philhagen** [comment]
admittedly cosmetic request.  Could it show the following instead of the native regex?

`   --name value, -n value       The name that will be given to the ISO volume during USB creation. Examples: 101.21.1 or 102.21.2A [$NAME]`
