### ISSUE TITLE
Windows output not consistent with macOS

### ISSUE THREAD

**Issue by philhagen** [sans-sroc/integrity#42]
When running the windows binary, the output doesn't match the macOS version (still have to test the linux version).
![2021-05-17_11-48-39](https://user-images.githubusercontent.com/428886/118518146-d6b77980-b705-11eb-8d8d-f97cf7d770fd.png)

![2021-05-17_11-47-42](https://user-images.githubusercontent.com/428886/118518036-c0a9b900-b705-11eb-92ec-f3c4b67e1907.png)

**Comment by philhagen** [comment]
seems to be a universal difference:
![2021-05-17_11-51-50](https://user-images.githubusercontent.com/428886/118518627-50e7fe00-b706-11eb-8175-c9c0f850a374.png)

**Comment by ekristen** [comment]
The output you are seeing on windows is the raw output, the macos is the pretty print. I will look into why the pretty print isn't working on windows, suspect its something to do with windows terminal not being POSIX.

**Comment by philhagen** [comment]
LGTM
