### ISSUE TITLE
Add a flag for custom `integrity` log file name

### ISSUE THREAD

**Issue by WebBreacher** [sans-sroc/integrity#49]
Many of us have multiple versions of our files that we need to run integrity on. Every time it is run, it creates a log file with the same name, overwriting previous versions of that file. I suggest creating a `-l <filename>` flag that can be passed so that a custom file name can be created for the log.

In case you are wondering, yes, I renamed the integrity.yml file with a custom name and the validation failed even though the SHA256 sums matched.

**Comment by ekristen** [comment]
I’m guessing you are asking to be able the change the name of the file created or file used for validation that contains the metadata and the file hashes to something other than sans-integrity.yml? 

I say guess because you mention a log file, but we don’t create or write a log file. 

I believe it was specifically a design decision to not allow that to prevent end user confusion and problems running the tool. 

@philhagen can talk to that topic specifically.

**Comment by philhagen** [comment]
unfortunately, we can't change that name - the filename must be predictable and consistent for a variety of downstream processing steps.

**Comment by philhagen** [comment]
oh - and yes, the design decision was to minimize all command line options and customization options to simplify the author's process and documentation/support...  this was a significant feedback item for bitfit in the past.

**Comment by WebBreacher** [comment]
Sorry for the lack of specifics. Yes. the sans-integrity.yml file name was what i was referring to. 

Understand about downstream processes.

Question though...if the YML file is present and the `validate` flag is provided to integrity, it fails because it cannot find the properly-named sans-integrity.yml file? Because the output I got (attached) shows a failure but does not mention "File not found". Perhaps verbose error messages could help here as I'd imagine that others will be making the same mistake I did and renaming the YML file? 
![image](https://user-images.githubusercontent.com/2359093/132584952-a8a17ee7-ecc0-4f4a-af8b-8326266467a0.png)

**Comment by philhagen** [comment]
ah interesting - if I'm interpreting what you said correctly, it would be preferable for a `validate` command to fail immediately if there is no `sans-integrity.yml` file present at all, correct?

**Comment by WebBreacher** [comment]
Not just fail immediately but verbosely: `We cannot find the sans-integrity.yml file. in the target directory.` because when I saw the validity check fail, I thought the file was corrupt. Then I checked the SHA256 inside the YML file against a manually-calculated SHA256 sum and saw they were correct. Then I had no idea why it didn't validate.

**Comment by ekristen** [comment]
That would be easy enough to do @philhagen

**Comment by philhagen** [comment]
Roger - that does make sense and sounds like an easy fix.  Thanks for clarifying @WebBreacher!  @ekristen yeah let's push this one out whenever there is a break in the action

**Comment by ekristen** [comment]
Resolved by https://github.com/sans-sroc/integrity/pull/50
