### ISSUE TITLE
directory separators cause failure for cross-platform validation

### ISSUE THREAD

**Issue by philhagen** [sans-sroc/integrity#7]
if checksum file is created on windows and validated on Mac/linux, every file fails

```
in /Volumes/511.21.1 
   integrity -c 511.21.1 -v -p
...
[!] Validation failed! File has been added!
    File: labs/bootcamp/snort/rules/emerging-icmp.rules
    Hash: 58ecd7de880fbd2e79ed2ee8968276f258aa88d1517305d26f44c14b4359ba60
...
[!] Validation failed! Original file missing!
    File: labs\bootcamp\snort\rules\emerging-icmp.rules
    Hash: 58ecd7de880fbd2e79ed2ee8968276f258aa88d1517305d26f44c14b4359ba60
...
[+] Validation process complete!
[!] Result: FAIL!
```

needs to validate cross-platform

**Comment by ryananicholson** [comment]
Easiest fix was to find/replace all `\` with `/` when generating the VERSION files. This work? If so, I'll release 1.0.7.

**Comment by philhagen** [comment]
that will work - but since we have the SEC511 ISO in production that uses `\`, what should we do?

I *think* I'm ok leaving this as a known failed validation... But are there any unintended consequences?

**Comment by ryananicholson** [comment]
We could, when verifying, find/replace as well so it'll work with older versions' VERSION files created on Windows?

**Comment by philhagen** [comment]
got it.  I'm ok with that, and maybe a future task/reminder that we can back that fix out at some point a year or so in the future.

could you also see if there is a more code-based method to replace those separators than find/replace?  what if there is a back slash as part of the filename?  how would this fix apply to special characters in the file name/path that need to be escaped?  (Despite the absolutely HORRID practice that would be....)

**Comment by ekristen** [comment]
We could standardize on a parseable format in like yaml that we can then version like v1, v2 if we change it and using golang parse to normalized relative path structure that doesn’t care about path separators.
